development:
  sessions:
    default:
      database: people_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
test:
  sessions:
    default:
      database: people_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
production:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_PEOPLE_URL'] %>
  options:
