index_pages:
  - index
  - start
  - api
  - community
titles:
  'start': Introducing Lelylan
  'start/introduction': Getting Started
  'start/app': Building your first app
  'start/physical': Connect your first device
  'start/tutorials': Tutorials & Articles
  'start/projects': Projects
  'api': Lelylan API
  'api/core': Core Concepts
  'api/devices': Devices
  'api/devices/consumptions': Consumptions
  'api/devices/histories': Histories
  'api/types': Types
  'api/types/properties': Properties
  'api/types/functions': Functions
  'api/types/statuses': Statuses
  'api/locations': Locations
  'api/activations': Activations
  'api/oauth': OAuth 2.0
  'api/realtime': Realtime
  'api/physicals': Physical Devices
  'api/physicals/nodes': Physical nodes
  'community': Community
  'community/clients': Client Libraries
  'community/support': Support
  'community/faq': Frequently Asked Questions
code_pages:
  - api/core
  - api/devices
  - api/devices/activations
  - api/devices/consumptions
  - api/devices/histories
  - api/types
  - api/types/properties
  - api/types/functions
  - api/types/statuses
  - api/locations
  - api/realtime
  - api/physicals
  - api/oauth
