index_pages:
  - index
  - start
  - api
  - community
titles:
  'start': Getting Started
  'start/introduction': Introduction
  'start/first-app': Build your First App
  'start/first-physical': Connect your First Device
  'start/tutorials': Tutorials & Articles
  'start/showcases': Showcases
  'api': Lelylan API
  'api/core': Core Concepts
  'api/devices': Devices
  'api/devices/consumptions': Consumptions
  'api/devices/histories': Histories
  'api/devices/activations': Activations
  'api/types': Types
  'api/types/properties': Properties
  'api/types/functions': Functions
  'api/types/statuses': Statuses
  'api/locations': Locations
  'api/oauth': OAuth 2.0
  'api/realtime': Realtime
  'api/physicals': Physical devices
  'api/physicals/nodes': Physical nodes
  'community': Community
  'community/clients': Client Libraries
  'community/support': Support
  'community/faq': Frequently Asked Questions
code_pages:
  - api/core
  - api/devices
  - api/devices/activations
  - api/devices/consumptions
  - api/devices/histories
  - api/types
  - api/types/properties
  - api/types/functions
  - api/types/statuses
  - api/locations
  - api/realtime
  - api/physicals
  - api/oauth
